using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TOTO.Data
{
    public class Prognosis
    {
        [Key] // Mark the property as the primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Specify that the value is generated by the database
        public int Id { get; set; }

        public int CustomersExpected { get; set; }
        public int ColliExpected { get; set; }

        [Column(TypeName = "Date")]
        public DateTime PrognosisDate { get; set; }
    }
}
