// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TOTO.Data;

#nullable disable

namespace TOTO.Data.Migrations
{
    [DbContext(typeof(TOTODBContext))]
    [Migration("20230927100216_Prognosis")]
    partial class Prognosis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TOTO.Data.Prognosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColliExpected")
                        .HasColumnType("int");

                    b.Property<int>("CustomersExpected")
                        .HasColumnType("int");

                    b.Property<DateTime>("PrognosisDate")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.ToTable("Prognosis");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ColliExpected = 50,
                            CustomersExpected = 353,
                            PrognosisDate = new DateTime(2023, 7, 9, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -2,
                            ColliExpected = 49,
                            CustomersExpected = 279,
                            PrognosisDate = new DateTime(2023, 7, 10, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -3,
                            ColliExpected = 37,
                            CustomersExpected = 288,
                            PrognosisDate = new DateTime(2023, 7, 11, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -4,
                            ColliExpected = 49,
                            CustomersExpected = 244,
                            PrognosisDate = new DateTime(2023, 7, 12, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -5,
                            ColliExpected = 36,
                            CustomersExpected = 415,
                            PrognosisDate = new DateTime(2023, 7, 13, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -6,
                            ColliExpected = 32,
                            CustomersExpected = 315,
                            PrognosisDate = new DateTime(2023, 7, 14, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -7,
                            ColliExpected = 60,
                            CustomersExpected = 368,
                            PrognosisDate = new DateTime(2023, 7, 15, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -8,
                            ColliExpected = 42,
                            CustomersExpected = 450,
                            PrognosisDate = new DateTime(2023, 7, 16, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -9,
                            ColliExpected = 36,
                            CustomersExpected = 362,
                            PrognosisDate = new DateTime(2023, 7, 17, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -10,
                            ColliExpected = 49,
                            CustomersExpected = 393,
                            PrognosisDate = new DateTime(2023, 7, 18, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -11,
                            ColliExpected = 43,
                            CustomersExpected = 222,
                            PrognosisDate = new DateTime(2023, 7, 19, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -12,
                            ColliExpected = 47,
                            CustomersExpected = 376,
                            PrognosisDate = new DateTime(2023, 7, 20, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -13,
                            ColliExpected = 36,
                            CustomersExpected = 414,
                            PrognosisDate = new DateTime(2023, 7, 21, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -14,
                            ColliExpected = 56,
                            CustomersExpected = 306,
                            PrognosisDate = new DateTime(2023, 7, 22, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -15,
                            ColliExpected = 34,
                            CustomersExpected = 387,
                            PrognosisDate = new DateTime(2023, 7, 23, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -16,
                            ColliExpected = 52,
                            CustomersExpected = 349,
                            PrognosisDate = new DateTime(2023, 7, 24, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -17,
                            ColliExpected = 55,
                            CustomersExpected = 468,
                            PrognosisDate = new DateTime(2023, 7, 25, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -18,
                            ColliExpected = 49,
                            CustomersExpected = 447,
                            PrognosisDate = new DateTime(2023, 7, 26, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -19,
                            ColliExpected = 43,
                            CustomersExpected = 301,
                            PrognosisDate = new DateTime(2023, 7, 27, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -20,
                            ColliExpected = 35,
                            CustomersExpected = 369,
                            PrognosisDate = new DateTime(2023, 7, 28, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -21,
                            ColliExpected = 37,
                            CustomersExpected = 420,
                            PrognosisDate = new DateTime(2023, 7, 29, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -22,
                            ColliExpected = 47,
                            CustomersExpected = 465,
                            PrognosisDate = new DateTime(2023, 7, 30, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -23,
                            ColliExpected = 31,
                            CustomersExpected = 348,
                            PrognosisDate = new DateTime(2023, 7, 31, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -24,
                            ColliExpected = 35,
                            CustomersExpected = 456,
                            PrognosisDate = new DateTime(2023, 8, 1, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -25,
                            ColliExpected = 36,
                            CustomersExpected = 443,
                            PrognosisDate = new DateTime(2023, 8, 2, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -26,
                            ColliExpected = 53,
                            CustomersExpected = 275,
                            PrognosisDate = new DateTime(2023, 8, 3, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -27,
                            ColliExpected = 33,
                            CustomersExpected = 430,
                            PrognosisDate = new DateTime(2023, 8, 4, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -28,
                            ColliExpected = 32,
                            CustomersExpected = 354,
                            PrognosisDate = new DateTime(2023, 8, 5, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -29,
                            ColliExpected = 50,
                            CustomersExpected = 438,
                            PrognosisDate = new DateTime(2023, 8, 6, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -30,
                            ColliExpected = 51,
                            CustomersExpected = 266,
                            PrognosisDate = new DateTime(2023, 8, 7, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -31,
                            ColliExpected = 39,
                            CustomersExpected = 392,
                            PrognosisDate = new DateTime(2023, 8, 8, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -32,
                            ColliExpected = 31,
                            CustomersExpected = 241,
                            PrognosisDate = new DateTime(2023, 8, 9, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -33,
                            ColliExpected = 35,
                            CustomersExpected = 360,
                            PrognosisDate = new DateTime(2023, 8, 10, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -34,
                            ColliExpected = 48,
                            CustomersExpected = 364,
                            PrognosisDate = new DateTime(2023, 8, 11, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -35,
                            ColliExpected = 51,
                            CustomersExpected = 392,
                            PrognosisDate = new DateTime(2023, 8, 12, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -36,
                            ColliExpected = 50,
                            CustomersExpected = 418,
                            PrognosisDate = new DateTime(2023, 8, 13, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -37,
                            ColliExpected = 47,
                            CustomersExpected = 311,
                            PrognosisDate = new DateTime(2023, 8, 14, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -38,
                            ColliExpected = 53,
                            CustomersExpected = 461,
                            PrognosisDate = new DateTime(2023, 8, 15, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -39,
                            ColliExpected = 35,
                            CustomersExpected = 459,
                            PrognosisDate = new DateTime(2023, 8, 16, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -40,
                            ColliExpected = 47,
                            CustomersExpected = 325,
                            PrognosisDate = new DateTime(2023, 8, 17, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -41,
                            ColliExpected = 57,
                            CustomersExpected = 222,
                            PrognosisDate = new DateTime(2023, 8, 18, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -42,
                            ColliExpected = 41,
                            CustomersExpected = 490,
                            PrognosisDate = new DateTime(2023, 8, 19, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -43,
                            ColliExpected = 57,
                            CustomersExpected = 335,
                            PrognosisDate = new DateTime(2023, 8, 20, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -44,
                            ColliExpected = 38,
                            CustomersExpected = 452,
                            PrognosisDate = new DateTime(2023, 8, 21, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -45,
                            ColliExpected = 53,
                            CustomersExpected = 273,
                            PrognosisDate = new DateTime(2023, 8, 22, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -46,
                            ColliExpected = 48,
                            CustomersExpected = 222,
                            PrognosisDate = new DateTime(2023, 8, 23, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -47,
                            ColliExpected = 56,
                            CustomersExpected = 232,
                            PrognosisDate = new DateTime(2023, 8, 24, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -48,
                            ColliExpected = 59,
                            CustomersExpected = 219,
                            PrognosisDate = new DateTime(2023, 8, 25, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -49,
                            ColliExpected = 58,
                            CustomersExpected = 414,
                            PrognosisDate = new DateTime(2023, 8, 26, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -50,
                            ColliExpected = 35,
                            CustomersExpected = 362,
                            PrognosisDate = new DateTime(2023, 8, 27, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -51,
                            ColliExpected = 51,
                            CustomersExpected = 231,
                            PrognosisDate = new DateTime(2023, 8, 28, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -52,
                            ColliExpected = 38,
                            CustomersExpected = 385,
                            PrognosisDate = new DateTime(2023, 8, 29, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -53,
                            ColliExpected = 30,
                            CustomersExpected = 240,
                            PrognosisDate = new DateTime(2023, 8, 30, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -54,
                            ColliExpected = 53,
                            CustomersExpected = 332,
                            PrognosisDate = new DateTime(2023, 8, 31, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -55,
                            ColliExpected = 39,
                            CustomersExpected = 356,
                            PrognosisDate = new DateTime(2023, 9, 1, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -56,
                            ColliExpected = 42,
                            CustomersExpected = 353,
                            PrognosisDate = new DateTime(2023, 9, 2, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -57,
                            ColliExpected = 54,
                            CustomersExpected = 453,
                            PrognosisDate = new DateTime(2023, 9, 3, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -58,
                            ColliExpected = 49,
                            CustomersExpected = 331,
                            PrognosisDate = new DateTime(2023, 9, 4, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -59,
                            ColliExpected = 30,
                            CustomersExpected = 296,
                            PrognosisDate = new DateTime(2023, 9, 5, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -60,
                            ColliExpected = 30,
                            CustomersExpected = 361,
                            PrognosisDate = new DateTime(2023, 9, 6, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -61,
                            ColliExpected = 33,
                            CustomersExpected = 416,
                            PrognosisDate = new DateTime(2023, 9, 7, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -62,
                            ColliExpected = 34,
                            CustomersExpected = 361,
                            PrognosisDate = new DateTime(2023, 9, 8, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -63,
                            ColliExpected = 53,
                            CustomersExpected = 207,
                            PrognosisDate = new DateTime(2023, 9, 9, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -64,
                            ColliExpected = 45,
                            CustomersExpected = 488,
                            PrognosisDate = new DateTime(2023, 9, 10, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -65,
                            ColliExpected = 39,
                            CustomersExpected = 365,
                            PrognosisDate = new DateTime(2023, 9, 11, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -66,
                            ColliExpected = 34,
                            CustomersExpected = 344,
                            PrognosisDate = new DateTime(2023, 9, 12, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -67,
                            ColliExpected = 30,
                            CustomersExpected = 482,
                            PrognosisDate = new DateTime(2023, 9, 13, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -68,
                            ColliExpected = 55,
                            CustomersExpected = 307,
                            PrognosisDate = new DateTime(2023, 9, 14, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -69,
                            ColliExpected = 43,
                            CustomersExpected = 401,
                            PrognosisDate = new DateTime(2023, 9, 15, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -70,
                            ColliExpected = 31,
                            CustomersExpected = 348,
                            PrognosisDate = new DateTime(2023, 9, 16, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -71,
                            ColliExpected = 40,
                            CustomersExpected = 415,
                            PrognosisDate = new DateTime(2023, 9, 17, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -72,
                            ColliExpected = 42,
                            CustomersExpected = 382,
                            PrognosisDate = new DateTime(2023, 9, 18, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -73,
                            ColliExpected = 48,
                            CustomersExpected = 471,
                            PrognosisDate = new DateTime(2023, 9, 19, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -74,
                            ColliExpected = 54,
                            CustomersExpected = 398,
                            PrognosisDate = new DateTime(2023, 9, 20, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -75,
                            ColliExpected = 57,
                            CustomersExpected = 409,
                            PrognosisDate = new DateTime(2023, 9, 21, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -76,
                            ColliExpected = 40,
                            CustomersExpected = 221,
                            PrognosisDate = new DateTime(2023, 9, 22, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -77,
                            ColliExpected = 39,
                            CustomersExpected = 285,
                            PrognosisDate = new DateTime(2023, 9, 23, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -78,
                            ColliExpected = 60,
                            CustomersExpected = 331,
                            PrognosisDate = new DateTime(2023, 9, 24, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -79,
                            ColliExpected = 52,
                            CustomersExpected = 244,
                            PrognosisDate = new DateTime(2023, 9, 25, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -80,
                            ColliExpected = 44,
                            CustomersExpected = 212,
                            PrognosisDate = new DateTime(2023, 9, 26, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -81,
                            ColliExpected = 58,
                            CustomersExpected = 272,
                            PrognosisDate = new DateTime(2023, 9, 27, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -82,
                            ColliExpected = 46,
                            CustomersExpected = 487,
                            PrognosisDate = new DateTime(2023, 9, 28, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -83,
                            ColliExpected = 48,
                            CustomersExpected = 324,
                            PrognosisDate = new DateTime(2023, 9, 29, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -84,
                            ColliExpected = 48,
                            CustomersExpected = 248,
                            PrognosisDate = new DateTime(2023, 9, 30, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -85,
                            ColliExpected = 39,
                            CustomersExpected = 360,
                            PrognosisDate = new DateTime(2023, 10, 1, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -86,
                            ColliExpected = 55,
                            CustomersExpected = 222,
                            PrognosisDate = new DateTime(2023, 10, 2, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -87,
                            ColliExpected = 37,
                            CustomersExpected = 479,
                            PrognosisDate = new DateTime(2023, 10, 3, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -88,
                            ColliExpected = 42,
                            CustomersExpected = 230,
                            PrognosisDate = new DateTime(2023, 10, 4, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -89,
                            ColliExpected = 53,
                            CustomersExpected = 308,
                            PrognosisDate = new DateTime(2023, 10, 5, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -90,
                            ColliExpected = 31,
                            CustomersExpected = 264,
                            PrognosisDate = new DateTime(2023, 10, 6, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -91,
                            ColliExpected = 30,
                            CustomersExpected = 215,
                            PrognosisDate = new DateTime(2023, 10, 7, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -92,
                            ColliExpected = 35,
                            CustomersExpected = 478,
                            PrognosisDate = new DateTime(2023, 10, 8, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -93,
                            ColliExpected = 59,
                            CustomersExpected = 397,
                            PrognosisDate = new DateTime(2023, 10, 9, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -94,
                            ColliExpected = 47,
                            CustomersExpected = 452,
                            PrognosisDate = new DateTime(2023, 10, 10, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -95,
                            ColliExpected = 51,
                            CustomersExpected = 466,
                            PrognosisDate = new DateTime(2023, 10, 11, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -96,
                            ColliExpected = 47,
                            CustomersExpected = 425,
                            PrognosisDate = new DateTime(2023, 10, 12, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -97,
                            ColliExpected = 44,
                            CustomersExpected = 382,
                            PrognosisDate = new DateTime(2023, 10, 13, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -98,
                            ColliExpected = 34,
                            CustomersExpected = 279,
                            PrognosisDate = new DateTime(2023, 10, 14, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -99,
                            ColliExpected = 58,
                            CustomersExpected = 479,
                            PrognosisDate = new DateTime(2023, 10, 15, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        },
                        new
                        {
                            Id = -100,
                            ColliExpected = 32,
                            CustomersExpected = 411,
                            PrognosisDate = new DateTime(2023, 10, 16, 12, 2, 16, 740, DateTimeKind.Local).AddTicks(1864)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
